language: node_js

node_js:
  - 8
  - 10
  - 12

install:
  - bash -x scripts/install.sh

script:
  - bash -x scripts/test.sh
  - bash -x scripts/lint.sh
  - node packages/ethereum-cryptography/scripts/check-browser-field.js

cache:
  npm: true
  directories:
    - $HOME/.npm
    - packages/ethereum-cryptography/node_modules
    - packages/ethereum-cryptography-native/node_modules
