language: node_js

node_js:
  - 10
  - 12
  - 13
  - 14

install:
  - npm i

script:
  - npm run test
  - npm run browser-tests
  - npm run lint
  - npm run build && node scripts/check-browser-field.js

cache:
  npm: true
  directories:
    - $HOME/.npm
    - node_modules
